# Require manifest, in dependency order. `require "./activity_weather/*"`
# would load alphabetically, which breaks whenever a file needs a type
# defined in a file that sorts after it — so the order is spelled out.
require "./activity_weather/version"
require "./activity_weather/annotations"
require "./activity_weather/concurrent"
require "./activity_weather/svg/builder"
require "./activity_weather/github/http_pool"
require "./activity_weather/github/api_client"
require "./activity_weather/committer"
require "./activity_weather/activity"
require "./activity_weather/metrics"
require "./activity_weather/weather"
require "./activity_weather/meteorologist"
require "./activity_weather/period"
require "./activity_weather/theme"
require "./activity_weather/config"
require "./activity_weather/inputs"
require "./activity_weather/svg/rng"
require "./activity_weather/palettes"
require "./activity_weather/animations"
require "./activity_weather/icons"
require "./activity_weather/renderers/renderer"
require "./activity_weather/renderers/card"
require "./activity_weather/renderers/forecast"
require "./activity_weather/renderers/banner"
require "./activity_weather/renderers/terminal"
require "./activity_weather/renderers/minimal"
require "./activity_weather/runner"
require "./activity_weather/cli"
